### ISSUE TITLE
There is no mode to display time in 24h format?

### ISSUE THREAD

**Issue by ferminako** [jtsage/jquery-mobile-datebox#278]
Hi I'm using your date box to display the time, but there is not timeFormat option to display the time in 24h format instead of 12h AM/PM into input controllers, because in the modal popup  it is already show in 24h format.
I've found timeOutput and I've tried:
 <input name="mytime"  id="mytime" type="time" data-role="datebox" placeholder="Time"
                       data-options='{"mode": "timeflipbox", "minuteStep":15 , "timeOutput"=24}'>

but it hasn't worked.

any solution?
Thx.

**Comment by shahabkamali** [comment]
I used something like this:

<input type="time" data-clear-btn="false" name="time" id="time" value="" data-role="datebox"
                 data-option='{ "overrideTimeFormat": 24, "overrideTimeOutput": "%k:%M" }' /></div>

but it does not work :|
