### ISSUE TITLE
TimeBox +/- buttons don't work in Chrome+Win8 (w/ repButton)

### ISSUE THREAD

**Issue by aljachimiak** [jtsage/jquery-mobile-datebox#304]
Using Chrome on Windows 8.1, our team found that the plus and minus buttons weren't working for timeBox and durationBox.

Adding `repButton: false` to the options seemed to clear up the issue.

Just thought I would drop the issue here because I haven't found it documented anywhere else.

**Comment by celron** [comment]
This appears to affect the flipbox/timeflipbox as well on windows 8 chrome, which unfortunately doesn't have the repButton: false option.
I'm not sure if this points to the problem, but I noticed in the debugger that the g variable (this.drag) is filled with a mixture of different events under chrome vs firefox, in that it had some touch events mixed with mouse events in chrome, while they were all mouse events in firefox.

**Comment by jtsage** [comment]
well that's interesting.  Thanks, that gives me a very useful avenue to persue now.

**Comment by jtsage** [comment]
oh.  OH.  https://support.mozilla.org/en-US/questions/994191  and https://hacks.mozilla.org/2013/04/detecting-touch-its-the-why-not-the-how/  

This is dumb on my part - I am using the classic hack to enable touch vs. mouse events - and IE broke it.  Not shocking, but there that is.  Working on a fix.

**Comment by jtsage** [comment]
I just pushed a possible fix - rather than listening to mouse *or* touch events, listen to both - already was doing this on the "end" event - basically I took the feature test for touch out.  If this works, I'll re-push version 1.4.5 - as of right now, only available here: http://cdn.jtsage.com/datebox/latest/

(not in the download builder).

Please, anyone with the hardware, let me know.  as of now, works as expected on chrome/firefox/safari mac os x, and iphone 5s.

**Comment by jtsage** [comment]
Also tested on win8 + firefox and IE.  Cannot reproduce incorrect behavior at this point, but I'd love to hear from @aljachimiak and @celron before I close.

**Comment by celron** [comment]
Using the patch I tried with both the datebox and timebox on my original test case without the repButton fix and the flipbox and timeflipbox and it works fine under chrome and windows 8.  Good work.

Hopefully the others will get to try it, but I think it'll work for them.
