### ISSUE TITLE
Is there an option for DateBox to close when clicking outside the popup or hitting ESC?

### ISSUE THREAD

**Issue by kevgrig** [jtsage/jquery-mobile-datebox#363]
Wonderful project, thank you!

JQueryMobile normally supports closing a popup by clicking outside of it or hitting the ESC key. For example: http://api.jquerymobile.com/resources/popup/example1.html

The default behavior of jQM DateBox doesn't seem to do this. I found a blog post that suggests there's a closeEscape option but I couldn't find this documented and it didn't work when I tried it:

> Press ESC to close, configurable with option 'closeEscape'

http://dev.jtsage.com/blog/jqm-datebox

**Comment by jtsage** [comment]
Yeah, it's there, it's just kind hidden.

Set useModal: false (which sets the popup dismissible option to true...)

http://dev.jtsage.com/jQM-DateBox/api/useModal/

**Comment by kevgrig** [comment]
That worked, thanks!
