### ISSUE TITLE
Register the library in the Bower registry

### ISSUE THREAD

**Issue by bgaillard** [jtsage/jquery-mobile-datebox#364]
Hi, it seems the library is not registered in the Bower registry http://bower.io/search/?q=datebox.

The guide which explains how to do it is here : http://bower.io/docs/creating-packages. Changing the version scheme in the library could be necessary to be compliant with semantic versionning (http://semver.org/).

Temporarily if someone wants to pull the library using bower here is how to do it in your `bower.json` file.

``` javascript
{
   ...
   "dependencies" : {
        ...
        "jquery-mobile-datebox" : "https://github.com/jtsage/jquery-mobile-datebox.git#jQM-1.4.5",
        ...
    }
    ...
}
```

**Comment by jtsage** [comment]
Well, changing how I write the version scheme isn't particularly difficult.  My question is - is it typical of bower to pull un-built libraries?  

(i.e., the .js files in the js folder are working versions - you *can* use them direct, but you'd need to already have a handle on how the library works - how is this typically done with bower?)  

To put it another way - got any similar library I can go look at the bower.json file of?  Thanks!

**Comment by kuehn-sba** [comment]
if you add a "build" or "dist" folder inside your repo. there you can place any pre-build js versions within the frameworks you using...

**Comment by calfzhou** [comment]
+1 for bower registry

**Comment by jtsage** [comment]
Ok, finally got around to this, I'll add a bit to the install docs next time around.

    bower install jtsage-datebox

**Comment by jtsage** [comment]
As a sidenote, there are also npm packages now.  Rather than list them all:

https://www.npmjs.com/~jtsage

Chances are, you want jtsage-datebox-<framework>, and jtsage-datebox-i18n
