### ISSUE TITLE
Popup is created outside the data-role="page" element

### ISSUE THREAD

**Issue by Andree643** [jtsage/jquery-mobile-datebox#373]
The popup is created outside the div[data-role="page"] element. This cause the popups aren't cleaned after page is changed and remain unreferenced and never cleaned up.
![datebox-popup-outside-page-issue](https://cloud.githubusercontent.com/assets/6212595/6525301/4671b070-c404-11e4-92f2-e738cb938f39.png)

**Comment by jtsage** [comment]
Yes.  and Indeed, those created on the first loaded page are not.  Subsequent pages *should* be cleaning up after themselves.  At least, they appear to be.

**Comment by jtsage** [comment]
For what it's worth, I couldn't find anywhere where I actually add the popup *to* the page.  It appear to me that the popup widget is doing it for me.
