### ISSUE TITLE
Plugin breaks and throws undef error when it can't find a.ui-input-clear

### ISSUE THREAD

**Issue by wardtwits** [jtsage/jquery-mobile-datebox#374]
Uncaught TypeError: Cannot read property 'tooltip' of undefined - caused by line # 1028 of jqm-datebox.core.js

The plugin seems to be appending a tooltip to an anchor tag, but blows up if its not there.  It should probably check first to see if the element is available.

**Comment by jtsage** [comment]
Version?  This does not appear at that place in the current version - however, 

property "tooltip" is usually indicative of a problem with loading a language file - either it's incomplete or corrupt.

The other thing that frequently causes this sort of thing to happen is a bad list of options - improper quoting usually.

If you have a sample somewhere, I'd be happy to look it over.
