### ISSUE TITLE
Popup position ignored for some reason

### ISSUE THREAD

**Issue by squaredonut** [jtsage/jquery-mobile-datebox#375]
I'm not sure if I'm doing this wrong, but with a simple page and a simple input, the calendar's don't seem to be poppping up in the center of the window, rather it's stuck relative to the center of the input box.

Could it be related to using jquery grid?

Here's a sample markup of mine

    <div class="ui-grid-a">
        <div class="ui-block-a" style="padding:0; border:0;margin:0;width: 70% !important;">
            <div class="ui-bar" style="padding:0; border:0;margin:0;">
                <input id="startDateTextBox" class="form-entry" data-options='{ "mode": "flipbox", "popupPosition": "window","useFocus": true, "showInitialValue" : true }' />
            </div>
        </div>
        <div class="ui-block-b" style="padding:0; border:0;margin:0;width: 30% !important;">
            <div class="ui-bar" style="padding:0; border:0;margin:0;">
                <input id="startTimeTextBox" class="form-entry" style="margin:0;"  type="text" data-role="datebox" data-options='{ "mode": "timeflipbox", "popupPosition": "window", "buttonIcon": "ui-icon-clock", "useModal" : true, "useFocus": true, "showInitialValue" : true }' />
            </div>
        </div>
    </div>

**Comment by jtsage** [comment]
Hmm.  Just used your code, and I was unable to reproduce.  Can you set up a jsFiddle maybe?
