### ISSUE TITLE
CSS style on Set date button

### ISSUE THREAD

**Issue by zahari4i** [jtsage/jquery-mobile-datebox#377]
I noticed a width issue on the set date button (datebox mode). The button has a width of 77px set in the css:
.ui-datebox-controls div {
  width: 77px;
  text-align: center;
  display: inline-block;
  zoom: 1;
}
so the button only shows the icon and the first letter on the button text.
Is there any particular reason why the width is not set to 100%?
Thanks

**Comment by jtsage** [comment]
Version?  (my guess is that it isn't -latest or 1.4.5, as this CSS does not seem to appear there)
