### ISSUE TITLE
Open datebox from JQM Popup

### ISSUE THREAD

**Issue by Soulcyber** [jtsage/jquery-mobile-datebox#378]
is there a way to open the datebox from an input text inside a JQM popup?
because pretty all datepicker widgets doesn't support it...

**Comment by jtsage** [comment]
Short answer: No, not really.  DateBox actually *is* a JQM Popup - and they are not nestable at this time.  Perhaps in the future this will be changed, but I doubt it.

For now, my not totally helpful suggestion is to use inline mode in a popup, that indeed does work as expected.
