### ISSUE TITLE
Setting defaultValue with Arabic language results in exception

### ISSUE THREAD

**Issue by dpolivy** [jtsage/jquery-mobile-datebox#380]
Using jQM Datebox 1.4.5 with the "ar" i18n file.

`defaultValue` is set to an ISO formatted date (e.g. `2015-07-22`).

When initializing the datebox on this HTML input, it throws an exception:
`Unable to get property 'length' of undefined or null reference` [source](https://github.com/jtsage/jquery-mobile-datebox/blob/master/js/jqm-datebox.core.js#L416)

It appears as though in this case, [_makeDate](https://github.com/jtsage/jquery-mobile-datebox/blob/master/js/jqm-datebox.core.js#L487) is called without a parameter, which then calls the `_dRep` function with undefined. Should it be using the `defVal` instead?

The code path all starts in [create](https://github.com/jtsage/jquery-mobile-datebox/blob/master/js/jqm-datebox.core.js#L1008).

**Comment by jtsage** [comment]
That bit of function is actually responsible for making sure we are not feeding unicode digits to the date function - I suspect there are not any browsers out there that will enjoy it.  I've thrown a fix for this in (commit next), and I suspect all is well now - what I can't tell is if defaultValue is working while using ar, as reading arabic is not even almost in my skill set.  My guess is that it is, as the display when I set a defaultValue differs from when I don't, but I'm just not sure.

**Comment by dpolivy** [comment]
This fix does appear to address the exception. I don't speak/read Arabic either, but doing some basic sanity testing with Google Translate, it does appear to be working properly.

**Comment by jtsage** [comment]
Brilliant, thanks for checking.
