### ISSUE TITLE
Ghost event on touch devices.

### ISSUE THREAD

**Issue by d00001** [jtsage/jquery-mobile-datebox#381]
I have a timebox with the following markup:

```
{"mode":"timebox", "useInline": true, "useSetButton":false, "hideInput": true, "useImmediate": true }
```

Clicking on any +/- causes the value to be incremented multiple times sometimes it keeps changing until I click the opposite action. Setting useImmediate to false solves this.

This only happens on touch devices (iOS/Android)

**Comment by jtsage** [comment]
Yar. Every time I find a good solution for this, *somebody* updates an OS (I'm looking at you Apple & Google), and it breaks again.  

Yes, the "fix" is to set useImmediate - I will work on a better fix.

**Comment by pascalverst** [comment]
Can you explain your fix or workaround?

Setting useImmediate: true causes this bug for me
Using an older library it just registers the increments twice, with the updated library it keeps increasing endlessly.

**Comment by jtsage** [comment]
I wrote "useImmediate", and I have no idea why.  I meant to write "repButton": false.  

My mistake. 

repButton: false uses a click per change model.  When it is true (the default), it attempts to detect when the button is held down - but on some devices, some of the time, DateBox will miss the mouseup event (or touchend, etc)

**Comment by AhsanRazaUK** [comment]
**repButton: false** works perfect.
I was able to replicate issue on Chrome small screen Emulators only (Never experienced on Firefox Emulators). And of course on real devices it always use to go till min/max date on one tap. **useImmediate: false** was not the option as on our design we couldn't use **useSetButton: true**. Thanks.
