### ISSUE TITLE
Can't get ISO format date when datebox is in Arabic mode

### ISSUE THREAD

**Issue by dpolivy** [jtsage/jquery-mobile-datebox#382]
I always need to be able to get the date in a standard ISO format (e.g. YYYY-MM-dd), regardless of the actual locale being shown to the user.

When Arabic is used, however, the value returned from `var date = this.callFormat('%Y-%m-%d', obj.date);` is in Arabic script.

Is there currently any way to retrieve an ISO formatted string in Latin characters when the Datebox culture is set to Arabic? If not, can this be added easily?

**Comment by jtsage** [comment]
Good idea.

I've changed the prototype of callFormat() a bit, added a 3rd argument to suppress the arabic-indic numeral replacement for those locales that enable it.

http://dev.jtsage.com/jQM-DateBox/api/callFormat/

Closed by SHA: a1a1783d36ee402f523a4fb2b7c3f8dc5e6b8750
