### ISSUE TITLE
timeflipbox rolloverMode set to false still rolls over

### ISSUE THREAD

**Issue by TannSan** [jtsage/jquery-mobile-datebox#385]
Hi, love the timeflipbox, it was perfect for my needs but there is a problem I have which is that when I set:

rolloverMode: { 'm': false, 'd': false, 'h': false, 'i': false, 's': false }

It does stop the time rolling over when I roll bottom-to-top but unfortunately it still rolls over when I do top-to-bottom.  So, to be clearer; when I scroll top-to-bottom on the minute slider it still changes the hour slider when I pass the beginning/end of the minute scroll.

I'm using v4.0.0 of the bootstrap flavor.

**Comment by jtsage** [comment]
Gross, thought I got all of these.  Stock options on timeflipbox otherwise?  Also, 12hr or 24hr clock?  (My apologies for the length of time - been a busy holiday season here)
