### ISSUE TITLE
Download builder

### ISSUE THREAD

**Issue by gregh3269** [jtsage/jquery-mobile-datebox#386]
Hello,

When I try the download builder for jqueryMobile & calBox only, I do not get a download, if I select all modes I do.

Cheers Greg.

**Comment by jtsage** [comment]
UPDATE: It appears *any* single mode doesn't work.  Huh.  Working on it now.

**Comment by gregh3269** [comment]
Thanks!, no problems upgrading also (jqm).

Cheers Greg
