### ISSUE TITLE
useAnimation has no effect

### ISSUE THREAD

**Issue by mscdex** [jtsage/jquery-mobile-datebox#392]
At least for flipbox and timeflipbox, [`useAnimation`](http://dev.jtsage.com/DateBox/api/useAnimation/) has no effect on widgets of those types. I found that I have to instead set `useAnimationTime: 0` in order to emulate `useAnimation: false`.

**Comment by mscdex** [comment]
I should also note that I'm using jquery UI.

**Comment by jtsage** [comment]
Good catch, looks like I missed a trap.  Functionally, that's all useAnimation is supposed to be doing in this context, now it will be.
