### ISSUE TITLE
Changing the Width and Height of the Timepicker

### ISSUE THREAD

**Issue by iArnoldo** [jtsage/jquery-mobile-datebox#395]
Hey, this is rather a question than an issue but, is there a way to change the height and width of the popup? I am using the timeflipbox mode.

Best regards

Arnold

**Comment by jtsage** [comment]
Yes, with custom CSS.  Depending on the CSS framework you are using:

http://dev.jtsage.com/DateBox/theme/bootstrap/

http://dev.jtsage.com/DateBox/theme/jqueryui/

http://dev.jtsage.com/DateBox/theme/jqm/

Width is in there, height is determined by content.  .ui-datebox-container is the parent element of everything, you could add padding there to control height a bit.

**Comment by iArnoldo** [comment]
Hey there, thanks a lot it worked perfectly. Sorry to bother you with another question but another thing that i couldnt find in the api is selecting time by clicking on the desired time in the timepicker and setting a predefined value in the timepicker rather then using the system time.

Best regards
Arnold

**Comment by jtsage** [comment]
No, I don't have it set up to allow clicking on other parts of the "wheel" to select time/date. The very first version of the plugin did, however, it led to a *lot* of unintentional input, particularly on touch devices.
