### ISSUE TITLE
Datebox / Timebox need two clicks on set button when editing input

### ISSUE THREAD

**Issue by zoulou2356** [jtsage/jquery-mobile-datebox#396]
**Steps to reproduce:**
1. Open a datebox / timebox
2. Click in a input and edit a value with the keyboard
3. Click on the Set button

**Actual result:**
- The focus is lost by the input and the "postrefresh" method occurs (a second click on the Set button is needed to close the datebox / timebox)

**Expected result:**
- Only one click on the Set button should be needed to close the datebox / timebox when editing an input with the keyboard

**Comment by jtsage** [comment]
This will hit with 4.1.0, likely later today.  Certainly in the next week.
