### ISSUE TITLE
Jquery UI version of DateBOX is not touchable on mobiles

### ISSUE THREAD

**Issue by ionluchian** [jtsage/jquery-mobile-datebox#399]
could u help me to make it touchable?

**Comment by ionluchian** [comment]
i am using this version

JTSage-DateBox-4.0.0 
jtsage-datebox-4.0.0.jqueryui.min.js

and using this way

`$(selector).datebox
    mode: effect
    overrideDateFormat: format
    useTodayButton: false
    useSetButton: true
    useTomorrowButton: false
    whiteDates: true
    useCancelButton: true
    useCollapsedBut: false
    afterToday: false
    useImmediate : true
    beforeToday: false
    maxYear: year
    openCallback: (data) ->
      $('.ui-datebox-container').append '<div class="ui-description-picker"><div class="custom_hide_800">' + i18n[lang]['id[8]'] + '</div><div class="ui-line-picker"></div></div>'
      $('input[type="text"][data-role="datebox"]').datebox 'refresh'
      return`

**Comment by iArnoldo** [comment]
jQueryUI is not supporting touchevents. But there is a little hack that makes this possible take a look here: http://touchpunch.furf.com/

**Comment by ionluchian** [comment]
thanks for the respond, i am using already this plugin but is not affecting the picker, anyway i switched to another plugin to use the timer as well.

I think will be a good idea if u cna find a hack for this to be touchable, i spend a lot of time with it, but didnt not work anyhting.

**Comment by jtsage** [comment]
The best advice I can give would be to mess with an events list on clickEvent and clickEventAlt - Without digging through all the code, I would guess that pretty much all of the jqueryUI click events use clickEventAlt.

That said, it appears to "just work" on iOS, so, what device/browser combo should I be checking instead (Just looked at the datebox and the flipbox modes)
