### ISSUE TITLE
calPrevMonth button trying to open new page when "afterToday":true

### ISSUE THREAD

**Issue by alexandredumat** [jtsage/jquery-mobile-datebox#401]
Hello,

I'm using phonegap on android 4.2.2, i have a calbox with "afterToday":true
When i click on the calPrevMonth button there is an attempt to go to file://android_asset/www/index.html# which i catch using the inappbrowser plugin and this piece of code :

    $('body').on('click','a',function(event){
        event.preventDefault();
        window.open($(this).attr("href"), '_system');
    });

How can i prevent that from happenig ?

Well for those interested here is the workaround :

    $('body').on('click','a',function(event){
        event.preventDefault();
        if ($(this).parent().parent().hasClass('ui-datebox-gridheader'))
            return;
        window.open($(this).attr("href"), '_system');
    });

**Comment by jtsage** [comment]
This shouldn't be happening.  My guess is there is a perfect storm somewhere between android, phonegap, and datebox. I am gonna drop a commit here that adds a stopPropegation, and a return false at the end of the previous/next month buttons.  I've never worked with phonegap, so I can't really help test this.

**Comment by alexandredumat** [comment]
Ok thanks,
As i mentionned in my post it is not urgent because i found an easy
workaround.

2017-01-04 18:31 GMT+01:00 J.T. Sage <notifications@github.com>:

**Comment by alexandredumat** [comment]
Test with download from http://dev.jtsage.com/DateBox/builder/
Problem not solved.
But as i said in my post there is an easy workaround so it's not that urgent

**Comment by jtsage** [comment]
For what it's worth, the builder is still using the 4.0.0 stable source.  If you want to test before I up the builder to the pending 4.1.0, you'd need to do it from the source repository.

**Comment by alexandredumat** [comment]
I'm sorry i'm not that used to github and i didn't manage to find a simple way of getting the equivalent of jtsage-datebox.min.js from the repository so i couldn't test...

**Comment by jtsage** [comment]
The builder is now updated.
