### ISSUE TITLE
Extend calFormatter argument with curMonth and curYear

### ISSUE THREAD

**Issue by slavap** [jtsage/jquery-mobile-datebox#406]
http://dev.jtsage.com/DateBox/api/calFormatter/

Two additional fields could simplify calFormatter implementation logic, because there is a difference between dates of currently selected month and dates from previous and next months (e.g. "Non-Month Day Color").

**Comment by jtsage** [comment]
I'm not sure I follow totally.  What info are you looking for inside that function, and as additional arguments, or in the special "date" object?

**Comment by slavap** [comment]
I mean in my calFormatter I have no enough info about input date. So curMonth and curYear should be in input param, so it will be: { Year, Month, Date, ISO, Comp, dateVisible, curMonth /* Integer, currently populated month */, curYear }
You already have these values in code, just pass them within calFormatter input param.
P.S. Also in code you have very long lines, it's hard to read, why not format code to max 120 symbols in line?

**Comment by jtsage** [comment]
Easy enough, added.  New version drops in a few hours.
