### ISSUE TITLE
Documentation for calYearPickMin and calYearPickMax is not clear enough.

### ISSUE THREAD

**Issue by slavap** [jtsage/jquery-mobile-datebox#407]
This statement: "< 1,800 :: Number of years from current year"
should be changed to: "from currently selected date's year"

Example: selected is today. calYearPickMin and calYearPickMax are both 10. In year picker 2007 - 2027 are populated. Select new date as 02/02/2027. In year picker 2017 - 2037 are populated.

**Comment by jtsage** [comment]
Huh.  Didn't know that I don't think. I will either update the documentation, or does it make more sense for it to be from "this year"?

**Comment by slavap** [comment]
@jtsage For me it looks like bug. It should be calculated from "now" year IMO, this always changing years interval in picker looks really strange.

**Comment by jtsage** [comment]
So, I couldn't really decide.  To me, having the scale sliding makes a lot of sense in most use cases, but I can see where having it the other way makes sense too.  So, a compromise, and a new option:

calYearPickRelative

Set it to true (the default) to keep the old behavior of a sliding scale based on the selected date. 

Set it to false to always base it on today's real date.
