### ISSUE TITLE
setTheDate() depends on current dateFormat

### ISSUE THREAD

**Issue by slavap** [jtsage/jquery-mobile-datebox#408]
Perhaps dateFormat should not be used if setTheDate() is called with Date object.

Example:
```html
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css"/>
    <link rel="stylesheet" href="http://cdn.jtsage.com/jtsage-datebox/4.1.1/jtsage-datebox-4.1.1.jqm.min.css"/>
    
    <script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <script src="http://cdn.jtsage.com/jtsage-datebox/4.1.1/jtsage-datebox-4.1.1.jqm.min.js"></script>
  </head>

  <body>
    <input id="calbox1" type="text" data-role="datebox" data-options='{"mode":"calbox", "overrideDateFormat":"%A %m/%d/%y"}'>
    <button id="setTheDateBtn">setTheDate: 02/15/2045</button>
    <input id="calbox2" type="text" data-role="datebox" data-options='{"mode":"calbox", "overrideDateFormat":"%A %m/%d/%Y"}'>
    
    <script>
      $(document).ready(function() {
        $("#setTheDateBtn").click(function() {
          var d = new Date(2045,02,15);
          $("#calbox1").datebox('setTheDate', d);
          $("#calbox2").datebox('setTheDate', d);
          var d1 = $("#calbox1").datebox('getTheDate');
          var d2 = $("#calbox2").datebox('getTheDate');
          alert("calbox1 value: " + d1 + "\n calbox2 value: " + d2);
        });
      });
    </script>
  </body>
</html>
```

**Comment by jtsage** [comment]
It shouldn't.  Hmm.  Good catch, I'll look at this.

**Comment by jtsage** [comment]
So, it looks like this *is* the behavoir - it does not in any way alter any "object" sent in, just gives it right to the internal date library.

What did take me forever with your above example, is there is no preventDefault or return false, so it was reloading the page when I hit the button, and made it look like it was failing.  

Do you have a browser/device combo I can try, and what I'm looking for, because I'm betting I'm missing something

Thanks

**Comment by slavap** [comment]
@jtsage Not sure I've got your question. It doesn't matter if you have preventDefault() and return false, or not. alert shows different values. May be this issue depends somehow from system locale?
![image](https://user-images.githubusercontent.com/4129763/27306145-695cdff0-54f9-11e7-9df1-b02d9dd4a97a.png)

**Comment by jtsage** [comment]
I finally see it now.

I got the same results, and then I thought I didn't once or twice - so, here is what is happening, and my proposed fix:

When you run setTheDate, it is taking a date object, setting the internal date to what you have given it, and spitting out the format you've specified.  Then, it runs the refresh() functionality to build / re-build the control - at which point it *read* the date in the input, using the format you've specified.  In this instance, calbox1 uses a 2 digit year, which I apparently hardcoded the "cut off" to be 2037 / 1938.  I'm not sure why I choose this, but, there it is. Perhaps I wanted to attempt to placate any older browsers still rocking a 32bit time system. 

In my looking, it appears that pretty much every program out there that handles 2 digits years does it a little bit differently.  So, what I am going to do is add an option "twoDigitYearCutoff" set by default to "38"

**Comment by slavap** [comment]
@jtsage  thanks, sounds good to me. And don't be too pessimistic about 21xx, there is 20% chance we will live longer :-)
