### ISSUE TITLE
jtsage for french

### ISSUE THREAD

**Issue by eliematta** [jtsage/jquery-mobile-datebox#409]
hi guys,

i ma using "jtsage-datebox.i18n.fr.utf8.js" where i am constructing the datebox in french mode and everything work fine.
Once i click on a specific date. the value of the date is equal for example "Avril12,2017"(Avril is similar to April in french language)
so what im doing in case of english(where value ="April12,2017"
def unformatActionDate(dateString)
     if !dateString.to_s.empty?
          dateObject = Date.strptime(dateString,%B %d, %Y)
          return dateObject.strftime("%d/%m/%Y");
     end
     return dateString
  end

when im doing the same for french(Avril12.2017) an issue appear in ruby code where Avril is not recognized as %B .

how can i use StrpTime for french ?

**Comment by jtsage** [comment]
Hmm.  I actually don't know any ruby at all, so I can't really offer any advice on that end.

However, have you considered submitting an unformatted / ISO date to make life easier?  Take a look at this page: http://dev.jtsage.com/DateBox/doc/7-1-formats/  It shows how to submit additional formats in text inputs, but it works just as well with hidden inputs. (The note about "linkedField" is particularly important, it does exactly this with no extra coding)
