### ISSUE TITLE
No support for selecting seconds

### ISSUE THREAD

**Issue by slominskir** [jtsage/jquery-mobile-datebox#410]
Enhancement request:  allow selecting Hours, Minutes, and Seconds in TimeBox / TimeFlipBox.

**Comment by slominskir** [comment]
The DurationBox mode can be hacked to almost do what we want.  If you use the following configuration:

.datebox({mode: "durationbox", 
overrideSetDurationButtonLabel: "Set Time", 
overrideDurationLabel: ["Day", "Hour", "Minute", "Second"], 
overrideDurationFormat: "%Dl:%DM:%DS",
overrideDurationOrder: ['h','i', 's']});

jQuery.extend(jQuery.jtsage.datebox.prototype.options, {
    'maxDur': 86399
});

The duration mode feature where a field wraps around to the next/previous unit if a limit is reached may not be optimal though.

**Comment by jtsage** [comment]
I believe this is sorted now.  This version will get pushed out the door later today probably (including to the builder).  If something doesn't work as expected, please open another ticket, thanks!
